// GENERATED by `pnpm gen:external-modules`. Do not edit.
// 外部模块（modules/*）的 client manifest 聚合。
import { bookmarkClientModule } from "@rewindom/bookmark/client/module.js";
import { noteClientModule } from "@rewindom/note/client/module.js";
import { shopClientModule } from "@rewindom/shop/client/module.js";
import { siteDocsClientModule } from "@rewindom/site-docs/client/module.js";
import { todoClientModule } from "@rewindom/todo/client/module.js";

import type { ClientAppModule } from "@rewindom/client-kit";

export const EXTERNAL_CLIENT_MODULES = [
  bookmarkClientModule,
  noteClientModule,
  shopClientModule,
  siteDocsClientModule,
  todoClientModule,
] as const satisfies readonly ClientAppModule[];
