// GENERATED by `pnpm gen:external-modules`. Do not edit.
// 外部模块（packages/external-modules/*）的 client manifest 聚合。
import { exampleExternalClientModule } from "@be-water/example-external/client/module.js";
import type { ClientAppModule } from "@be-water/client-kit";

export const EXTERNAL_CLIENT_MODULES = [
  exampleExternalClientModule,
] as const satisfies readonly ClientAppModule[];
