// GENERATED by `pnpm gen:external-modules`. Do not edit.
// 外部模块（packages/external-modules/*）的 server manifest 聚合。
// 内部模块仍在 enabled-modules.ts 里手写；本文件只管外部。
import { exampleExternalServerModule } from "@be-water/example-external/server/index.js";
import type { ServerAppModule } from "@be-water/server-kernel/runtime/module-contract.js";

export const EXTERNAL_SERVER_MODULES = [
  exampleExternalServerModule,
] as const satisfies readonly ServerAppModule[];
