// GENERATED by `pnpm gen:external-modules`. Do not edit.
// 外部模块（modules/*）的 server manifest 聚合。
// 内部模块仍在 enabled-modules.ts 里手写；本文件只管外部。
import { bookmarkServerModule } from "@be-water/bookmark/server/index.js";
import { noteServerModule } from "@be-water/note/server/index.js";
import { todoServerModule } from "@be-water/todo/server/index.js";

import type { ServerAppModule } from "@be-water/server-kernel/runtime/module-contract.js";

export const EXTERNAL_SERVER_MODULES = [
  bookmarkServerModule,
  noteServerModule,
  todoServerModule,
] as const satisfies readonly ServerAppModule[];
