import {
  BarChart3,
  Heading1,
  CircleHelp,
  Columns2,
  FileText,
  Grid2x2,
  Layout,
  LayoutList,
  LayoutPanelTop,
  LibraryBig,
  Link2,
  List,
  ListOrdered,
  ListTree,
  Megaphone,
  PanelBottom,
  PanelTop,
  RectangleHorizontal,
  RectangleVertical,
  Rows3,
  TextCursorInput,
  Sparkles,
  Table2,
  Tag,
  Text,
  TriangleAlert,
  type LucideIcon,
} from "lucide-react";

import type { SectionType } from "../../../shared/section-schema.js";

/** 图标是纯展示层关注点，不进 shared schema。 */
export const SECTION_ICONS: Record<SectionType, LucideIcon> = {
  header: PanelTop,
  footer: PanelBottom,
  "page-header": Heading1,
  hero: LayoutPanelTop,
  "feature-grid": Grid2x2,
  steps: ListOrdered,
  "spec-list": Table2,
  cards: Layout,
  "page-menu": LayoutList,
  pricing: Tag,
  faq: CircleHelp,
  form: TextCursorInput,
  prose: Text,
  "doc-source": FileText,
  "doc-list": LibraryBig,
  "doc-article": FileText,
  "doc-nav": ListTree,
  "doc-toc": List,
  group: Columns2,
  band: Megaphone,
  // 这份代码不认识的段：树上要看得见、能选中、能删，所以给它一个明确的警示图标
  unsupported: TriangleAlert,
};

export const BLOCK_ICONS: Record<string, LucideIcon> = {
  column: RectangleVertical,
  card: RectangleHorizontal,
  stat: BarChart3,
  feature: Sparkles,
  step: ListOrdered,
  row: Rows3,
  plan: Tag,
  qa: CircleHelp,
  field: TextCursorInput,
  nav_link: Link2,
  footer_link: Link2,
};
