import type { EntityKind } from "../event/entity-extractor.js";

import type { EventSourceKind, EventTopic } from "../../shared/index.js";

export interface FeedSeed {
  connector: string;
  name: string;
  url: string;
  source_kind: EventSourceKind;
  topic: EventTopic;
  /**
   * 这个源的**出版方实体**——「这条源发的事，是关于谁的」。
   *
   * 只给一手来源填（official / release / status / filing）。一篇 TechCrunch
   * 报道不是「关于 TechCrunch」的，给 news 源填出版方会把每个媒体变成一个
   * 实体聚合面——正好是实体抽取那几道闸要挡的东西的放大版。
   *
   * **显式写，不用剥后缀的规则猜**：`AWS Machine Learning` → AWS、
   * `Bank of England` → Bank of England、`Kubernetes Releases` → Kubernetes，
   * 三条没有一条能被同一个规则做对。`feed-catalog.test.ts` 钉住
   * 「每个一手来源目录项都有 publisher_entity」，新增源时忘了填会红。
   *
   * 存在的理由：归位与累计档案要求事件上有主实体，而实体抽取刻意保守
   *（Title Case 整条弃权、句首要等印证），本地库量到的覆盖率——
   * release 8.3%、status 36.4%、official 38.0%。而这批事件的实体**根本不用猜**：
   * `Cloudflare Status` 的事件就是关于 Cloudflare 的。
   */
  publisher_entity?: { name: string; kind: EntityKind };
}

/**
 * 内置采集源目录。
 *
 * 一期只接 Hacker News 与 RSS/Atom 两个 connector（见 MVP §12：不追求全网）。
 *
 * 种植口径见 `feed-seed.ts`：按**目录项的 key** 记录「这个站点种过什么」，
 * 只种从未种过的——既能给存量站点补新源，又不会把站点删掉的源塞回来。
 *
 * 为什么要铺到这个量：跨源印证是这个产品的核心，而它受制于
 * 「HN 上那条帖子有没有第二个源覆盖到」。8 个源时线上 16 张卡有 13 张只有单一来源。
 * 每个 topic 至少 3 个源——单源 topic 的事件永远无法跨源印证，等于白占一个筛选项。
 * ai / tech / business 刻意更密：同一件事更容易被第二家源接到。
 * world / gaming / entertainment / sports 也曾偏薄，后来按同一口径补过报道与一手源
 * （Steam 是 gaming 里少有的 official；娱乐与体育仍然没有「当事方公告」的等价物，
 * 硬凑一个不如空着）。
 *
 * 明确不加：Anthropic / Meta AI 官网没有官方 RSS（第三方刮来的镜像不进目录）；
 * Wired 主 feed 目前是优惠码；Reuters 已关公开 RSS；Politico 对阅读器 UA 403；
 * Stripe 没有公开 blog/status RSS；Azure 状态页 feed 解析不出条目。
 *
 * 目录里的每个 URL 都实际请求验证过。**已知在部分网络环境下不可达**：
 * `GitHub Blog` 与 `Hugging Face` 在本地会 `terminated`（连接被中断，不是 404），
 * 生产机房可能正常——这是既有目录里就存在的现象，不是新增源引入的。
 * 单个源失败不影响整轮采集，错误记在 `EventFeed.last_error` 上。
 *
 * **非新闻源**（release / status / filing）是刻意的差异化落点，见文件末尾那一组。
 * 它们的存在也解释了目录里为什么会有「同一家公司两条源」——博客是它在说什么，
 * 状态页是它的系统在发生什么，两者不是一回事。
 *
 * 中文源仍然不加：分词器对中文走二元切分、对英文走词切分，
 * 中英标题 token 交集恒为 0。语义层已经就位（见 MODULE.md「语义聚类」），
 * 但跨语言合并要单独校准阈值，属于独立决策。
 */

/** 目录项的稳定身份。改 name / source_kind 不会让站点重新种一遍。 */
export function feedCatalogKey(feed: {
  connector: string;
  url: string;
}): string {
  return `${feed.connector}:${feed.url}`;
}
export const HACKER_NEWS_API_ROOT = "https://hacker-news.firebaseio.com/v0";

export const DEFAULT_FEEDS: readonly FeedSeed[] = [
  {
    connector: "hackernews",
    name: "Hacker News",
    // 内置 connector 不读这个地址，只是拿它当唯一键
    url: HACKER_NEWS_API_ROOT,
    source_kind: "community",
    topic: "tech",
  },

  // ---- ai · 一手来源：当事方自己说的话
  {
    connector: "rss",
    name: "OpenAI",
    url: "https://openai.com/news/rss.xml",
    source_kind: "official",
    topic: "ai",
    publisher_entity: { name: "OpenAI", kind: "company" },
  },
  {
    connector: "rss",
    name: "Hugging Face",
    url: "https://huggingface.co/blog/feed.xml",
    source_kind: "official",
    topic: "ai",
    publisher_entity: { name: "Hugging Face", kind: "company" },
  },
  {
    connector: "rss",
    name: "Google Research",
    url: "https://research.google/blog/rss/",
    source_kind: "official",
    topic: "ai",
    publisher_entity: { name: "Google", kind: "company" },
  },
  {
    connector: "rss",
    name: "DeepMind",
    url: "https://deepmind.google/blog/rss.xml",
    source_kind: "official",
    topic: "ai",
    publisher_entity: { name: "DeepMind", kind: "company" },
  },
  {
    connector: "rss",
    name: "Google AI Blog",
    url: "https://blog.google/technology/ai/rss/",
    source_kind: "official",
    topic: "ai",
    publisher_entity: { name: "Google", kind: "company" },
  },
  {
    connector: "rss",
    name: "NVIDIA Blog",
    url: "https://blogs.nvidia.com/feed/",
    source_kind: "official",
    topic: "ai",
    publisher_entity: { name: "NVIDIA", kind: "company" },
  },
  {
    connector: "rss",
    name: "Microsoft Research",
    url: "https://www.microsoft.com/en-us/research/feed/",
    source_kind: "official",
    topic: "ai",
    publisher_entity: { name: "Microsoft", kind: "company" },
  },
  {
    connector: "rss",
    name: "PyTorch Blog",
    url: "https://pytorch.org/blog/feed.xml",
    source_kind: "official",
    topic: "ai",
    publisher_entity: { name: "PyTorch", kind: "product" },
  },
  {
    connector: "rss",
    name: "AWS Machine Learning",
    url: "https://aws.amazon.com/blogs/machine-learning/feed/",
    source_kind: "official",
    topic: "ai",
    publisher_entity: { name: "AWS", kind: "company" },
  },
  // 第三轮补：上一轮判死的几家换了地址（Mistral / Databricks / Allen AI），
  // 外加学界与厂商的一手研究博客
  {
    connector: "rss",
    name: "Allen Institute for AI",
    url: "https://allenai.org/rss.xml",
    source_kind: "official",
    topic: "ai",
    publisher_entity: { name: "Allen Institute for AI", kind: "org" },
  },
  {
    connector: "rss",
    name: "Apple Machine Learning",
    url: "https://machinelearning.apple.com/rss.xml",
    source_kind: "official",
    topic: "ai",
    publisher_entity: { name: "Apple", kind: "company" },
  },
  {
    connector: "rss",
    name: "BAIR Blog",
    url: "https://bair.berkeley.edu/blog/feed.xml",
    source_kind: "official",
    topic: "ai",
    publisher_entity: { name: "Berkeley AI Research", kind: "org" },
  },
  {
    connector: "rss",
    name: "Databricks Blog",
    url: "https://www.databricks.com/feed",
    source_kind: "official",
    topic: "ai",
    publisher_entity: { name: "Databricks", kind: "company" },
  },
  {
    connector: "rss",
    name: "Mistral AI",
    url: "https://mistral.ai/rss.xml",
    source_kind: "official",
    topic: "ai",
    publisher_entity: { name: "Mistral AI", kind: "company" },
  },
  {
    connector: "rss",
    name: "MIT News AI",
    url: "https://news.mit.edu/rss/topic/artificial-intelligence2",
    source_kind: "official",
    topic: "ai",
    publisher_entity: { name: "MIT", kind: "org" },
  },
  {
    connector: "rss",
    name: "Ollama Blog",
    url: "https://ollama.com/blog/rss.xml",
    source_kind: "official",
    topic: "ai",
    publisher_entity: { name: "Ollama", kind: "product" },
  },

  // ---- ai · 报道
  {
    connector: "rss",
    name: "MIT Technology Review",
    url: "https://www.technologyreview.com/feed/",
    source_kind: "news",
    topic: "ai",
  },
  {
    connector: "rss",
    name: "VentureBeat AI",
    url: "https://venturebeat.com/category/ai/feed/",
    source_kind: "news",
    topic: "ai",
  },
  {
    connector: "rss",
    name: "IEEE Spectrum AI",
    url: "https://spectrum.ieee.org/feeds/topic/artificial-intelligence.rss",
    source_kind: "news",
    topic: "ai",
  },

  // ---- tech · 一手来源
  {
    connector: "rss",
    name: "GitHub Blog",
    url: "https://github.blog/feed/",
    source_kind: "official",
    topic: "tech",
    publisher_entity: { name: "GitHub", kind: "company" },
  },
  {
    connector: "rss",
    name: "Cloudflare Blog",
    url: "https://blog.cloudflare.com/rss/",
    source_kind: "official",
    topic: "tech",
    publisher_entity: { name: "Cloudflare", kind: "company" },
  },
  {
    connector: "rss",
    name: "Mozilla Hacks",
    url: "https://hacks.mozilla.org/feed/",
    source_kind: "official",
    topic: "tech",
    publisher_entity: { name: "Mozilla", kind: "org" },
  },
  {
    connector: "rss",
    name: "Chromium Blog",
    url: "https://blog.chromium.org/feeds/posts/default",
    source_kind: "official",
    topic: "tech",
    publisher_entity: { name: "Chromium", kind: "product" },
  },
  {
    connector: "rss",
    name: "Rust Blog",
    url: "https://blog.rust-lang.org/feed.xml",
    source_kind: "official",
    topic: "tech",
    publisher_entity: { name: "Rust", kind: "product" },
  },
  {
    connector: "rss",
    name: "Stack Overflow Blog",
    url: "https://stackoverflow.blog/feed/",
    source_kind: "official",
    topic: "tech",
    publisher_entity: { name: "Stack Overflow", kind: "company" },
  },
  {
    connector: "rss",
    name: "Meta Engineering",
    url: "https://engineering.fb.com/feed/",
    source_kind: "official",
    topic: "tech",
    publisher_entity: { name: "Meta", kind: "company" },
  },
  {
    connector: "rss",
    name: "AWS News Blog",
    url: "https://aws.amazon.com/blogs/aws/feed/",
    source_kind: "official",
    topic: "tech",
    publisher_entity: { name: "AWS", kind: "company" },
  },
  {
    connector: "rss",
    name: "Microsoft DevBlogs",
    url: "https://devblogs.microsoft.com/feed/",
    source_kind: "official",
    topic: "tech",
    publisher_entity: { name: "Microsoft", kind: "company" },
  },
  {
    connector: "rss",
    name: "Apple Newsroom",
    url: "https://www.apple.com/newsroom/rss-feed.rss",
    source_kind: "official",
    topic: "tech",
    publisher_entity: { name: "Apple", kind: "company" },
  },
  {
    connector: "rss",
    name: "GitLab Blog",
    url: "https://about.gitlab.com/atom.xml",
    source_kind: "official",
    topic: "tech",
    publisher_entity: { name: "GitLab", kind: "company" },
  },
  {
    connector: "rss",
    name: "Kubernetes Blog",
    url: "https://kubernetes.io/feed.xml",
    source_kind: "official",
    topic: "tech",
    publisher_entity: { name: "Kubernetes", kind: "product" },
  },
  {
    connector: "rss",
    name: "Docker Blog",
    url: "https://www.docker.com/blog/feed/",
    source_kind: "official",
    topic: "tech",
    publisher_entity: { name: "Docker", kind: "company" },
  },
  {
    connector: "rss",
    name: "Vercel Blog",
    url: "https://vercel.com/atom",
    source_kind: "official",
    topic: "tech",
    publisher_entity: { name: "Vercel", kind: "company" },
  },
  {
    connector: "rss",
    name: "Netflix Tech Blog",
    url: "https://netflixtechblog.com/feed",
    source_kind: "official",
    topic: "tech",
    publisher_entity: { name: "Netflix", kind: "company" },
  },
  // 第三轮补：开发者工具与运行时的官方博客，外加 CISA 安全公告（filing）
  {
    connector: "rss",
    name: "CISA Advisories",
    url: "https://www.cisa.gov/cybersecurity-advisories/all.xml",
    source_kind: "filing",
    topic: "tech",
    publisher_entity: { name: "CISA", kind: "org" },
  },
  {
    connector: "rss",
    name: "Android Developers Blog",
    url: "https://android-developers.googleblog.com/feeds/posts/default",
    source_kind: "official",
    topic: "tech",
    publisher_entity: { name: "Android", kind: "product" },
  },
  {
    connector: "rss",
    name: "Apple Developer News",
    url: "https://developer.apple.com/news/rss/news.rss",
    source_kind: "official",
    topic: "tech",
    publisher_entity: { name: "Apple", kind: "company" },
  },
  {
    connector: "rss",
    // 同上，184 条
    name: "Astro Blog",
    url: "https://astro.build/rss.xml",
    source_kind: "official",
    topic: "tech",
    publisher_entity: { name: "Astro", kind: "product" },
  },
  {
    connector: "rss",
    // 同上，177 条
    name: "Bun Blog",
    url: "https://bun.sh/rss.xml",
    source_kind: "official",
    topic: "tech",
    publisher_entity: { name: "Bun", kind: "product" },
  },
  {
    connector: "rss",
    // 同上，249 条
    name: "Deno Blog",
    url: "https://deno.com/feed",
    source_kind: "official",
    topic: "tech",
    publisher_entity: { name: "Deno", kind: "product" },
  },
  {
    connector: "rss",
    name: "Discord Blog",
    url: "https://discord.com/blog/rss.xml",
    source_kind: "official",
    topic: "tech",
    publisher_entity: { name: "Discord", kind: "company" },
  },
  {
    connector: "rss",
    name: "Dropbox Tech",
    url: "https://dropbox.tech/feed",
    source_kind: "official",
    topic: "tech",
    publisher_entity: { name: "Dropbox", kind: "company" },
  },
  {
    connector: "rss",
    name: "Fly.io Blog",
    url: "https://fly.io/blog/feed.xml",
    source_kind: "official",
    topic: "tech",
    publisher_entity: { name: "Fly.io", kind: "company" },
  },
  {
    connector: "rss",
    name: "Grafana Blog",
    url: "https://grafana.com/blog/index.xml",
    source_kind: "official",
    topic: "tech",
    publisher_entity: { name: "Grafana", kind: "product" },
  },
  {
    connector: "rss",
    name: "HashiCorp Blog",
    url: "https://www.hashicorp.com/blog/feed.xml",
    source_kind: "official",
    topic: "tech",
    publisher_entity: { name: "HashiCorp", kind: "company" },
  },
  {
    connector: "rss",
    name: "Intel Newsroom",
    url: "https://newsroom.intel.com/feed",
    source_kind: "official",
    topic: "tech",
    publisher_entity: { name: "Intel", kind: "company" },
  },
  {
    connector: "rss",
    name: "JetBrains Blog",
    url: "https://blog.jetbrains.com/feed/",
    source_kind: "official",
    topic: "tech",
    publisher_entity: { name: "JetBrains", kind: "company" },
  },
  {
    connector: "rss",
    name: "Mozilla Blog",
    url: "https://blog.mozilla.org/en/feed/",
    source_kind: "official",
    topic: "tech",
    publisher_entity: { name: "Mozilla", kind: "org" },
  },
  {
    connector: "rss",
    name: "PlanetScale Blog",
    url: "https://planetscale.com/blog/rss.xml",
    source_kind: "official",
    topic: "tech",
    publisher_entity: { name: "PlanetScale", kind: "company" },
  },
  {
    connector: "rss",
    // PostgreSQL 没有 GitHub releases，发版走官网 news
    name: "PostgreSQL News",
    url: "https://www.postgresql.org/news.rss",
    source_kind: "official",
    topic: "tech",
    publisher_entity: { name: "PostgreSQL", kind: "product" },
  },
  {
    connector: "rss",
    name: "Raspberry Pi",
    url: "https://www.raspberrypi.com/news/feed/",
    source_kind: "official",
    topic: "tech",
    publisher_entity: { name: "Raspberry Pi", kind: "company" },
  },
  {
    connector: "rss",
    name: "Samsung Newsroom",
    url: "https://news.samsung.com/global/feed",
    source_kind: "official",
    topic: "tech",
    publisher_entity: { name: "Samsung", kind: "company" },
  },
  {
    connector: "rss",
    name: "Slack Engineering",
    url: "https://slack.engineering/feed/",
    source_kind: "official",
    topic: "tech",
    publisher_entity: { name: "Slack", kind: "company" },
  },
  {
    connector: "rss",
    name: "Spotify Engineering",
    url: "https://engineering.atspotify.com/feed/",
    source_kind: "official",
    topic: "tech",
    publisher_entity: { name: "Spotify", kind: "company" },
  },
  {
    connector: "rss",
    name: "Stripe Blog",
    url: "https://stripe.com/blog/feed.rss",
    source_kind: "official",
    topic: "tech",
    publisher_entity: { name: "Stripe", kind: "company" },
  },
  {
    connector: "rss",
    // 全量归档（420 条，倒序）；前 40 条覆盖到一年多以前
    name: "Supabase Blog",
    url: "https://supabase.com/rss.xml",
    source_kind: "official",
    topic: "tech",
    publisher_entity: { name: "Supabase", kind: "company" },
  },
  {
    connector: "rss",
    name: "W3C News",
    url: "https://www.w3.org/blog/news/feed/",
    source_kind: "official",
    topic: "tech",
    publisher_entity: { name: "W3C", kind: "org" },
  },

  // ---- tech · 报道 / 社区
  {
    connector: "rss",
    name: "TechCrunch",
    url: "https://techcrunch.com/feed/",
    source_kind: "news",
    topic: "tech",
  },
  {
    connector: "rss",
    name: "The Verge",
    url: "https://www.theverge.com/rss/index.xml",
    source_kind: "news",
    topic: "tech",
  },
  {
    connector: "rss",
    name: "Ars Technica",
    url: "https://feeds.arstechnica.com/arstechnica/index",
    source_kind: "news",
    topic: "tech",
  },
  {
    connector: "rss",
    name: "Hacker Noon",
    url: "https://hackernoon.com/feed",
    source_kind: "news",
    topic: "tech",
  },
  {
    connector: "rss",
    name: "Engadget",
    url: "https://www.engadget.com/rss.xml",
    source_kind: "news",
    topic: "tech",
  },
  {
    connector: "rss",
    name: "The Register",
    url: "https://www.theregister.com/headlines.atom",
    source_kind: "news",
    topic: "tech",
  },
  {
    connector: "rss",
    name: "InfoQ",
    url: "https://feed.infoq.com",
    source_kind: "news",
    topic: "tech",
  },
  {
    connector: "rss",
    name: "Bloomberg Technology",
    url: "https://feeds.bloomberg.com/technology/news.rss",
    source_kind: "news",
    topic: "tech",
  },
  {
    connector: "rss",
    name: "WSJ Technology",
    url: "https://feeds.a.dj.com/rss/RSSWSJD.xml",
    source_kind: "news",
    topic: "tech",
  },
  {
    connector: "rss",
    name: "Lobsters",
    url: "https://lobste.rs/rss",
    source_kind: "community",
    topic: "tech",
  },

  // ---- business
  {
    connector: "rss",
    name: "BBC Business",
    url: "https://feeds.bbci.co.uk/news/business/rss.xml",
    source_kind: "news",
    topic: "business",
  },
  {
    connector: "rss",
    name: "Financial Times",
    url: "https://www.ft.com/rss/home",
    source_kind: "news",
    topic: "business",
  },
  {
    connector: "rss",
    name: "NPR Business",
    url: "https://feeds.npr.org/1006/rss.xml",
    source_kind: "news",
    topic: "business",
  },
  {
    connector: "rss",
    name: "CNBC Business",
    url: "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=10001147",
    source_kind: "news",
    topic: "business",
  },
  {
    connector: "rss",
    name: "Fortune",
    url: "https://fortune.com/feed/",
    source_kind: "news",
    topic: "business",
  },
  {
    connector: "rss",
    name: "Business Insider",
    url: "https://www.businessinsider.com/rss",
    source_kind: "news",
    topic: "business",
  },
  {
    connector: "rss",
    name: "Federal Reserve Press",
    url: "https://www.federalreserve.gov/feeds/press_all.xml",
    source_kind: "official",
    topic: "business",
    publisher_entity: { name: "Federal Reserve", kind: "org" },
  },
  {
    connector: "rss",
    name: "SEC Press Releases",
    url: "https://www.sec.gov/news/pressreleases.rss",
    source_kind: "filing",
    topic: "business",
    publisher_entity: { name: "SEC", kind: "org" },
  },
  // Akamai 会拦阅读器 UA，采集出口对 ftc.gov 改用浏览器族 UA（见 http.ts）
  {
    connector: "rss",
    name: "FTC Press Releases",
    url: "https://www.ftc.gov/feeds/press-release.xml",
    source_kind: "filing",
    topic: "business",
    publisher_entity: { name: "FTC", kind: "org" },
  },
  {
    connector: "rss",
    name: "FDA Press Releases",
    url: "https://www.fda.gov/about-fda/contact-fda/stay-informed/rss-feeds/press-releases/rss.xml",
    source_kind: "filing",
    topic: "business",
    publisher_entity: { name: "FDA", kind: "org" },
  },
  {
    connector: "rss",
    name: "ECB Press",
    url: "https://www.ecb.europa.eu/rss/press.html",
    source_kind: "official",
    topic: "business",
    publisher_entity: { name: "European Central Bank", kind: "org" },
  },

  // 第三轮补：报道面 + 监管机构（DOJ / CFPB / UK CMA）+ 大厂自己的新闻室
  {
    connector: "rss",
    name: "CFPB Newsroom",
    url: "https://www.consumerfinance.gov/about-us/newsroom/feed/",
    source_kind: "filing",
    topic: "business",
    publisher_entity: { name: "CFPB", kind: "org" },
  },
  {
    connector: "rss",
    name: "DOJ Press Releases",
    url: "https://www.justice.gov/news/rss?type=press_release",
    source_kind: "filing",
    topic: "business",
    publisher_entity: { name: "DOJ", kind: "org" },
  },
  {
    connector: "rss",
    name: "UK CMA",
    url: "https://www.gov.uk/government/organisations/competition-and-markets-authority.atom",
    source_kind: "filing",
    topic: "business",
    publisher_entity: { name: "CMA", kind: "org" },
  },
  {
    connector: "rss",
    name: "Axios",
    url: "https://api.axios.com/feed/",
    source_kind: "news",
    topic: "business",
  },
  {
    connector: "rss",
    name: "Forbes Business",
    url: "https://www.forbes.com/business/feed/",
    source_kind: "news",
    topic: "business",
  },
  {
    connector: "rss",
    name: "MarketWatch",
    url: "https://feeds.content.dowjones.io/public/rss/mw_topstories",
    source_kind: "news",
    topic: "business",
  },
  {
    connector: "rss",
    name: "Quartz",
    url: "https://qz.com/rss",
    source_kind: "news",
    topic: "business",
  },
  {
    connector: "rss",
    // 300 条倒序，前 40 条约五周
    name: "The Economist Business",
    url: "https://www.economist.com/business/rss.xml",
    source_kind: "news",
    topic: "business",
  },
  {
    connector: "rss",
    name: "Yahoo Finance",
    url: "https://finance.yahoo.com/news/rssindex",
    source_kind: "news",
    topic: "business",
  },
  {
    connector: "rss",
    name: "Amazon News",
    url: "https://www.aboutamazon.com/news/rss",
    source_kind: "official",
    topic: "business",
    publisher_entity: { name: "Amazon", kind: "company" },
  },
  {
    connector: "rss",
    name: "Bank of England",
    url: "https://www.bankofengland.co.uk/rss/news",
    source_kind: "official",
    topic: "business",
    publisher_entity: { name: "Bank of England", kind: "org" },
  },
  {
    connector: "rss",
    name: "Meta Newsroom",
    url: "https://about.fb.com/news/feed/",
    source_kind: "official",
    topic: "business",
    publisher_entity: { name: "Meta", kind: "company" },
  },
  {
    connector: "rss",
    name: "Microsoft Source",
    url: "https://news.microsoft.com/source/feed/",
    source_kind: "official",
    topic: "business",
    publisher_entity: { name: "Microsoft", kind: "company" },
  },

  // ---- world
  {
    connector: "rss",
    name: "BBC World",
    url: "https://feeds.bbci.co.uk/news/world/rss.xml",
    source_kind: "news",
    topic: "world",
  },
  {
    connector: "rss",
    name: "NPR World",
    url: "https://feeds.npr.org/1004/rss.xml",
    source_kind: "news",
    topic: "world",
  },
  {
    connector: "rss",
    name: "Al Jazeera",
    url: "https://www.aljazeera.com/xml/rss/all.xml",
    source_kind: "news",
    topic: "world",
  },
  {
    connector: "rss",
    name: "UN News",
    url: "https://news.un.org/feed/subscribe/en/news/all/rss.xml",
    source_kind: "official",
    topic: "world",
    publisher_entity: { name: "United Nations", kind: "org" },
  },
  {
    connector: "rss",
    name: "WHO Newsroom",
    url: "https://www.who.int/rss-feeds/news-english.xml",
    source_kind: "official",
    topic: "world",
    publisher_entity: { name: "WHO", kind: "org" },
  },
  {
    connector: "rss",
    name: "The Guardian World",
    url: "https://www.theguardian.com/world/rss",
    source_kind: "news",
    topic: "world",
  },
  {
    connector: "rss",
    name: "Deutsche Welle",
    url: "https://rss.dw.com/rdf/rss-en-world",
    source_kind: "news",
    topic: "world",
  },
  {
    connector: "rss",
    name: "France 24",
    url: "https://www.france24.com/en/rss",
    source_kind: "news",
    topic: "world",
  },
  {
    connector: "rss",
    name: "Foreign Policy",
    url: "https://foreignpolicy.com/feed/",
    source_kind: "news",
    topic: "world",
  },
  {
    connector: "rss",
    name: "Time",
    url: "https://time.com/feed/",
    source_kind: "news",
    topic: "world",
  },

  // 第三轮补：报道面 + 欧盟委员会公告 + NASA / 美国国务院
  {
    connector: "rss",
    name: "European Commission",
    url: "https://ec.europa.eu/commission/presscorner/api/rss?language=en&pagesize=20",
    source_kind: "filing",
    topic: "world",
    publisher_entity: { name: "European Commission", kind: "org" },
  },
  {
    connector: "rss",
    name: "ABC News (Australia)",
    url: "https://www.abc.net.au/news/feed/51120/rss.xml",
    source_kind: "news",
    topic: "world",
  },
  {
    connector: "rss",
    name: "Euronews",
    url: "https://www.euronews.com/rss",
    source_kind: "news",
    topic: "world",
  },
  {
    connector: "rss",
    name: "NYT World",
    url: "https://rss.nytimes.com/services/xml/rss/nyt/World.xml",
    source_kind: "news",
    topic: "world",
  },
  {
    connector: "rss",
    name: "Sky News World",
    url: "https://feeds.skynews.com/feeds/rss/world.xml",
    source_kind: "news",
    topic: "world",
  },
  {
    connector: "rss",
    // 只有 2 条，且实测 9~11s —— 目录里最慢的一条，做并发时优先关照
    name: "Washington Post World",
    url: "https://feeds.washingtonpost.com/rss/world",
    source_kind: "news",
    topic: "world",
  },
  {
    connector: "rss",
    name: "NASA News",
    url: "https://www.nasa.gov/news-release/feed/",
    source_kind: "official",
    topic: "world",
    publisher_entity: { name: "NASA", kind: "org" },
  },
  {
    connector: "rss",
    name: "US State Department",
    url: "https://www.state.gov/rss-feed/press-releases/feed/",
    source_kind: "official",
    topic: "world",
    publisher_entity: { name: "US State Department", kind: "org" },
  },

  // ---- gaming
  {
    connector: "rss",
    name: "Polygon",
    url: "https://www.polygon.com/rss/index.xml",
    source_kind: "news",
    topic: "gaming",
  },
  {
    connector: "rss",
    name: "Eurogamer",
    url: "https://www.eurogamer.net/feed",
    source_kind: "news",
    topic: "gaming",
  },
  {
    connector: "rss",
    name: "PlayStation Blog",
    url: "https://blog.playstation.com/feed/",
    source_kind: "official",
    topic: "gaming",
    publisher_entity: { name: "PlayStation", kind: "product" },
  },
  {
    connector: "rss",
    name: "Xbox Wire",
    url: "https://news.xbox.com/en-us/feed/",
    source_kind: "official",
    topic: "gaming",
    publisher_entity: { name: "Xbox", kind: "product" },
  },
  {
    connector: "rss",
    name: "Steam News",
    url: "https://store.steampowered.com/feeds/news.xml",
    source_kind: "official",
    topic: "gaming",
    publisher_entity: { name: "Steam", kind: "product" },
  },
  {
    connector: "rss",
    name: "IGN",
    url: "https://feeds.ign.com/ign/all",
    source_kind: "news",
    topic: "gaming",
  },
  {
    connector: "rss",
    name: "Rock Paper Shotgun",
    url: "https://www.rockpapershotgun.com/feed",
    source_kind: "news",
    topic: "gaming",
  },
  {
    connector: "rss",
    name: "PC Gamer",
    url: "https://www.pcgamer.com/rss/",
    source_kind: "news",
    topic: "gaming",
  },
  {
    connector: "rss",
    name: "Nintendo Life",
    url: "https://www.nintendolife.com/feeds/latest",
    source_kind: "news",
    topic: "gaming",
  },

  // 第三轮补：行业媒体 + 引擎方（Godot / Unreal）——这一格的 official 一直只有平台商
  {
    connector: "rss",
    name: "Game Developer",
    url: "https://www.gamedeveloper.com/rss.xml",
    source_kind: "news",
    topic: "gaming",
  },
  {
    connector: "rss",
    name: "GamesIndustry.biz",
    url: "https://www.gamesindustry.biz/feed",
    source_kind: "news",
    topic: "gaming",
  },
  {
    connector: "rss",
    name: "GameSpot",
    url: "https://www.gamespot.com/feeds/news/",
    source_kind: "news",
    topic: "gaming",
  },
  {
    connector: "rss",
    name: "Video Games Chronicle",
    url: "https://www.videogameschronicle.com/feed/",
    source_kind: "news",
    topic: "gaming",
  },
  {
    connector: "rss",
    name: "Godot Engine",
    url: "https://godotengine.org/rss.xml",
    source_kind: "official",
    topic: "gaming",
    publisher_entity: { name: "Godot", kind: "product" },
  },
  {
    connector: "rss",
    name: "Unreal Engine",
    url: "https://www.unrealengine.com/rss",
    source_kind: "official",
    topic: "gaming",
    publisher_entity: { name: "Unreal Engine", kind: "product" },
  },

  // ---- entertainment
  {
    connector: "rss",
    name: "Variety",
    url: "https://variety.com/feed/",
    source_kind: "news",
    topic: "entertainment",
  },
  {
    connector: "rss",
    name: "The Hollywood Reporter",
    url: "https://www.hollywoodreporter.com/feed/",
    source_kind: "news",
    topic: "entertainment",
  },
  {
    connector: "rss",
    name: "BBC Entertainment",
    url: "https://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml",
    source_kind: "news",
    topic: "entertainment",
  },
  {
    connector: "rss",
    name: "Deadline",
    url: "https://deadline.com/feed/",
    source_kind: "news",
    topic: "entertainment",
  },
  {
    connector: "rss",
    name: "Rolling Stone",
    url: "https://www.rollingstone.com/feed/",
    source_kind: "news",
    topic: "entertainment",
  },
  {
    connector: "rss",
    name: "Billboard",
    url: "https://www.billboard.com/feed/",
    source_kind: "news",
    topic: "entertainment",
  },
  {
    connector: "rss",
    name: "Pitchfork",
    url: "https://pitchfork.com/feed/feed-news/rss",
    source_kind: "news",
    topic: "entertainment",
  },

  // 第三轮补：行业媒体（Collider / Consequence / IndieWire / NME / Screen Rant /
  // TheWrap），以及这一格**第一次有的一手来源**——片方与流媒体自己发的公告
  // （Disney / Paramount / Spotify Newsroom / Sundance）。
  // MODULE.md 里「娱乐没有当事方公告的等价物」那句已作废
  {
    connector: "rss",
    name: "Collider",
    url: "https://collider.com/feed/",
    source_kind: "news",
    topic: "entertainment",
  },
  {
    connector: "rss",
    name: "Consequence",
    url: "https://consequence.net/feed/",
    source_kind: "news",
    topic: "entertainment",
  },
  {
    connector: "rss",
    name: "IndieWire",
    url: "https://www.indiewire.com/feed/",
    source_kind: "news",
    topic: "entertainment",
  },
  {
    connector: "rss",
    name: "NME",
    url: "https://www.nme.com/feed",
    source_kind: "news",
    topic: "entertainment",
  },
  {
    connector: "rss",
    name: "Screen Rant",
    url: "https://screenrant.com/feed/",
    source_kind: "news",
    topic: "entertainment",
  },
  {
    connector: "rss",
    name: "TheWrap",
    url: "https://www.thewrap.com/feed/",
    source_kind: "news",
    topic: "entertainment",
  },
  {
    connector: "rss",
    // 投资者关系稿，但内容是片方公告，归 entertainment
    name: "Paramount",
    url: "https://ir.paramount.com/rss/news-releases.xml",
    source_kind: "official",
    topic: "entertainment",
    publisher_entity: { name: "Paramount", kind: "company" },
  },
  {
    connector: "rss",
    name: "Spotify Newsroom",
    url: "https://newsroom.spotify.com/feed/",
    source_kind: "official",
    topic: "entertainment",
    publisher_entity: { name: "Spotify", kind: "company" },
  },
  {
    connector: "rss",
    name: "Sundance Institute",
    url: "https://www.sundance.org/feed/",
    source_kind: "official",
    topic: "entertainment",
    publisher_entity: { name: "Sundance Institute", kind: "org" },
  },
  {
    connector: "rss",
    name: "The Walt Disney Company",
    url: "https://thewaltdisneycompany.com/feed/",
    source_kind: "official",
    topic: "entertainment",
    publisher_entity: { name: "Disney", kind: "company" },
  },

  // ---- sports
  {
    connector: "rss",
    name: "BBC Sport",
    url: "https://feeds.bbci.co.uk/sport/rss.xml",
    source_kind: "news",
    topic: "sports",
  },
  {
    connector: "rss",
    name: "ESPN",
    url: "https://www.espn.com/espn/rss/news",
    source_kind: "news",
    topic: "sports",
  },
  {
    connector: "rss",
    name: "Sky Sports",
    url: "https://www.skysports.com/rss/12040",
    source_kind: "news",
    topic: "sports",
  },
  {
    connector: "rss",
    name: "The Guardian Sport",
    url: "https://www.theguardian.com/sport/rss",
    source_kind: "news",
    topic: "sports",
  },
  {
    connector: "rss",
    name: "CBS Sports",
    url: "https://www.cbssports.com/rss/headlines/",
    source_kind: "news",
    topic: "sports",
  },
  {
    connector: "rss",
    name: "The Athletic",
    url: "https://www.nytimes.com/athletic/rss/news/",
    source_kind: "news",
    topic: "sports",
  },

  // 第三轮补：报道面（Sporting News / Yahoo Sports），以及这一格**第一次有的
  // 一手来源**——联盟自己的稿子（MLB / Formula 1）。
  // **只有一部分联盟提供第一方 RSS**：NBA / NFL / NHL / FIFA / UEFA / 英超 /
  // 世界田联实测 403、404 或返回 JSON。不是「体育没有一手来源」，是这些联盟不发 RSS
  {
    connector: "rss",
    name: "Sporting News",
    url: "https://www.sportingnews.com/us/rss",
    source_kind: "news",
    topic: "sports",
  },
  {
    connector: "rss",
    name: "Yahoo Sports",
    url: "https://sports.yahoo.com/rss/",
    source_kind: "news",
    topic: "sports",
  },
  {
    connector: "rss",
    name: "Formula 1",
    url: "https://www.formula1.com/en/latest/all.xml",
    source_kind: "official",
    topic: "sports",
    publisher_entity: { name: "Formula 1", kind: "org" },
  },
  {
    connector: "rss",
    name: "MLB News",
    url: "https://www.mlb.com/feeds/news/rss.xml",
    source_kind: "official",
    topic: "sports",
    publisher_entity: { name: "MLB", kind: "org" },
  },

  /*
   * ---- 非新闻源 ----
   *
   * 竞品结构上不收这些——它们不是「新闻」。而对读者「这家昨天上线了什么、
   * 刚出过什么故障」往往比「媒体写了什么」更有用，这正是躲开对方强项的落点。
   *
   * 三类都有现成 RSS/Atom，现有 rss connector 直接吃，不需要新 connector。
   * 它们只按 canonical_url 归属，不参与文本聚类（见 shared 的 clustersByUrlOnly），
   * 也不进 Rising（恒为单来源，见 CROSS_SOURCE_KINDS）。
   */

  // ---- release · GitHub 的 releases.atom，每条 release 一个独立 permalink
  {
    connector: "rss",
    name: "Kubernetes Releases",
    url: "https://github.com/kubernetes/kubernetes/releases.atom",
    source_kind: "release",
    topic: "tech",
    publisher_entity: { name: "Kubernetes", kind: "product" },
  },
  {
    connector: "rss",
    name: "Rust Releases",
    url: "https://github.com/rust-lang/rust/releases.atom",
    source_kind: "release",
    topic: "tech",
    publisher_entity: { name: "Rust", kind: "product" },
  },
  {
    connector: "rss",
    name: "Node.js Releases",
    url: "https://github.com/nodejs/node/releases.atom",
    source_kind: "release",
    topic: "tech",
    publisher_entity: { name: "Node.js", kind: "product" },
  },
  {
    connector: "rss",
    name: "Go Releases",
    url: "https://github.com/golang/go/releases.atom",
    source_kind: "release",
    topic: "tech",
    publisher_entity: { name: "Go", kind: "product" },
  },
  {
    connector: "rss",
    name: "Python Releases",
    url: "https://github.com/python/cpython/releases.atom",
    source_kind: "release",
    topic: "tech",
    publisher_entity: { name: "Python", kind: "product" },
  },
  {
    connector: "rss",
    name: "TypeScript Releases",
    url: "https://github.com/microsoft/TypeScript/releases.atom",
    source_kind: "release",
    topic: "tech",
    publisher_entity: { name: "TypeScript", kind: "product" },
  },
  {
    connector: "rss",
    name: "React Releases",
    url: "https://github.com/facebook/react/releases.atom",
    source_kind: "release",
    topic: "tech",
    publisher_entity: { name: "React", kind: "product" },
  },
  {
    connector: "rss",
    name: "Redis Releases",
    url: "https://github.com/redis/redis/releases.atom",
    source_kind: "release",
    topic: "tech",
    publisher_entity: { name: "Redis", kind: "product" },
  },
  {
    connector: "rss",
    name: "Linux Kernel",
    url: "https://www.kernel.org/feeds/kdist.xml",
    source_kind: "release",
    topic: "tech",
    publisher_entity: { name: "Linux", kind: "product" },
  },

  // 第三轮补：主流运行时、框架与基础设施；ai 侧补训练/推理栈
  {
    connector: "rss",
    name: "LangChain Releases",
    url: "https://github.com/langchain-ai/langchain/releases.atom",
    source_kind: "release",
    topic: "ai",
    publisher_entity: { name: "LangChain", kind: "product" },
  },
  {
    connector: "rss",
    name: "Ollama Releases",
    url: "https://github.com/ollama/ollama/releases.atom",
    source_kind: "release",
    topic: "ai",
    publisher_entity: { name: "Ollama", kind: "product" },
  },
  {
    connector: "rss",
    name: "PyTorch Releases",
    url: "https://github.com/pytorch/pytorch/releases.atom",
    source_kind: "release",
    topic: "ai",
    publisher_entity: { name: "PyTorch", kind: "product" },
  },
  {
    connector: "rss",
    name: "TensorFlow Releases",
    url: "https://github.com/tensorflow/tensorflow/releases.atom",
    source_kind: "release",
    topic: "ai",
    publisher_entity: { name: "TensorFlow", kind: "product" },
  },
  {
    connector: "rss",
    name: "Transformers Releases",
    url: "https://github.com/huggingface/transformers/releases.atom",
    source_kind: "release",
    topic: "ai",
    publisher_entity: { name: "Transformers", kind: "product" },
  },
  {
    connector: "rss",
    name: "vLLM Releases",
    url: "https://github.com/vllm-project/vllm/releases.atom",
    source_kind: "release",
    topic: "ai",
    publisher_entity: { name: "vLLM", kind: "product" },
  },
  {
    connector: "rss",
    name: "Angular Releases",
    url: "https://github.com/angular/angular/releases.atom",
    source_kind: "release",
    topic: "tech",
    publisher_entity: { name: "Angular", kind: "product" },
  },
  {
    connector: "rss",
    name: "Ansible Releases",
    url: "https://github.com/ansible/ansible/releases.atom",
    source_kind: "release",
    topic: "tech",
    publisher_entity: { name: "Ansible", kind: "product" },
  },
  {
    connector: "rss",
    name: "Bun Releases",
    url: "https://github.com/oven-sh/bun/releases.atom",
    source_kind: "release",
    topic: "tech",
    publisher_entity: { name: "Bun", kind: "product" },
  },
  {
    connector: "rss",
    name: "ClickHouse Releases",
    url: "https://github.com/ClickHouse/ClickHouse/releases.atom",
    source_kind: "release",
    topic: "tech",
    publisher_entity: { name: "ClickHouse", kind: "product" },
  },
  {
    connector: "rss",
    name: "Deno Releases",
    url: "https://github.com/denoland/deno/releases.atom",
    source_kind: "release",
    topic: "tech",
    publisher_entity: { name: "Deno", kind: "product" },
  },
  {
    connector: "rss",
    name: "Django Releases",
    url: "https://github.com/django/django/releases.atom",
    source_kind: "release",
    topic: "tech",
    publisher_entity: { name: "Django", kind: "product" },
  },
  {
    connector: "rss",
    name: "DuckDB Releases",
    url: "https://github.com/duckdb/duckdb/releases.atom",
    source_kind: "release",
    topic: "tech",
    publisher_entity: { name: "DuckDB", kind: "product" },
  },
  {
    connector: "rss",
    name: "Elasticsearch Releases",
    url: "https://github.com/elastic/elasticsearch/releases.atom",
    source_kind: "release",
    topic: "tech",
    publisher_entity: { name: "Elasticsearch", kind: "product" },
  },
  {
    connector: "rss",
    name: "Electron Releases",
    url: "https://github.com/electron/electron/releases.atom",
    source_kind: "release",
    topic: "tech",
    publisher_entity: { name: "Electron", kind: "product" },
  },
  {
    connector: "rss",
    name: "Git Releases",
    url: "https://github.com/git/git/releases.atom",
    source_kind: "release",
    topic: "tech",
    publisher_entity: { name: "Git", kind: "product" },
  },
  {
    connector: "rss",
    name: "Grafana Releases",
    url: "https://github.com/grafana/grafana/releases.atom",
    source_kind: "release",
    topic: "tech",
    publisher_entity: { name: "Grafana", kind: "product" },
  },
  {
    connector: "rss",
    name: "Kafka Releases",
    url: "https://github.com/apache/kafka/releases.atom",
    source_kind: "release",
    topic: "tech",
    publisher_entity: { name: "Kafka", kind: "product" },
  },
  {
    connector: "rss",
    name: "Kotlin Releases",
    url: "https://github.com/JetBrains/kotlin/releases.atom",
    source_kind: "release",
    topic: "tech",
    publisher_entity: { name: "Kotlin", kind: "product" },
  },
  {
    connector: "rss",
    name: "Laravel Releases",
    url: "https://github.com/laravel/framework/releases.atom",
    source_kind: "release",
    topic: "tech",
    publisher_entity: { name: "Laravel", kind: "product" },
  },
  {
    connector: "rss",
    name: "Moby Releases",
    url: "https://github.com/moby/moby/releases.atom",
    source_kind: "release",
    topic: "tech",
    publisher_entity: { name: "Moby", kind: "product" },
  },
  {
    connector: "rss",
    name: "Next.js Releases",
    url: "https://github.com/vercel/next.js/releases.atom",
    source_kind: "release",
    topic: "tech",
    publisher_entity: { name: "Next.js", kind: "product" },
  },
  {
    connector: "rss",
    name: "Nginx Releases",
    url: "https://github.com/nginx/nginx/releases.atom",
    source_kind: "release",
    topic: "tech",
    publisher_entity: { name: "Nginx", kind: "product" },
  },
  {
    connector: "rss",
    name: "PHP Releases",
    url: "https://github.com/php/php-src/releases.atom",
    source_kind: "release",
    topic: "tech",
    publisher_entity: { name: "PHP", kind: "product" },
  },
  {
    connector: "rss",
    name: "pnpm Releases",
    url: "https://github.com/pnpm/pnpm/releases.atom",
    source_kind: "release",
    topic: "tech",
    publisher_entity: { name: "pnpm", kind: "product" },
  },
  {
    connector: "rss",
    name: "Prisma Releases",
    url: "https://github.com/prisma/prisma/releases.atom",
    source_kind: "release",
    topic: "tech",
    publisher_entity: { name: "Prisma", kind: "product" },
  },
  {
    connector: "rss",
    name: "Rails Releases",
    url: "https://github.com/rails/rails/releases.atom",
    source_kind: "release",
    topic: "tech",
    publisher_entity: { name: "Rails", kind: "product" },
  },
  {
    connector: "rss",
    // ruby-lang 官方 news，发版公告走这里（GitHub 那侧只有 tag，没有 release）
    name: "Ruby Releases",
    url: "https://www.ruby-lang.org/en/feeds/news.rss",
    source_kind: "release",
    topic: "tech",
    publisher_entity: { name: "Ruby", kind: "product" },
  },
  {
    connector: "rss",
    name: "Svelte Releases",
    url: "https://github.com/sveltejs/svelte/releases.atom",
    source_kind: "release",
    topic: "tech",
    publisher_entity: { name: "Svelte", kind: "product" },
  },
  {
    connector: "rss",
    name: "Swift Releases",
    url: "https://github.com/swiftlang/swift/releases.atom",
    source_kind: "release",
    topic: "tech",
    publisher_entity: { name: "Swift", kind: "product" },
  },
  {
    connector: "rss",
    name: "Tailwind CSS Releases",
    url: "https://github.com/tailwindlabs/tailwindcss/releases.atom",
    source_kind: "release",
    topic: "tech",
    publisher_entity: { name: "Tailwind CSS", kind: "product" },
  },
  {
    connector: "rss",
    name: "Terraform Releases",
    url: "https://github.com/hashicorp/terraform/releases.atom",
    source_kind: "release",
    topic: "tech",
    publisher_entity: { name: "Terraform", kind: "product" },
  },
  {
    connector: "rss",
    name: "Vite Releases",
    url: "https://github.com/vitejs/vite/releases.atom",
    source_kind: "release",
    topic: "tech",
    publisher_entity: { name: "Vite", kind: "product" },
  },
  {
    connector: "rss",
    name: "VS Code Releases",
    url: "https://github.com/microsoft/vscode/releases.atom",
    source_kind: "release",
    topic: "tech",
    publisher_entity: { name: "VS Code", kind: "product" },
  },
  {
    connector: "rss",
    name: "Vue Releases",
    url: "https://github.com/vuejs/core/releases.atom",
    source_kind: "release",
    topic: "tech",
    publisher_entity: { name: "Vue", kind: "product" },
  },
  {
    connector: "rss",
    name: "Zig Releases",
    url: "https://github.com/ziglang/zig/releases.atom",
    source_kind: "release",
    topic: "tech",
    publisher_entity: { name: "Zig", kind: "product" },
  },

  // ---- status · Statuspage 的 history.rss，每次故障一个独立 permalink
  {
    connector: "rss",
    name: "GitHub Status",
    url: "https://www.githubstatus.com/history.rss",
    source_kind: "status",
    topic: "tech",
    publisher_entity: { name: "GitHub", kind: "company" },
  },
  {
    connector: "rss",
    name: "Cloudflare Status",
    url: "https://www.cloudflarestatus.com/history.rss",
    source_kind: "status",
    topic: "tech",
    publisher_entity: { name: "Cloudflare", kind: "company" },
  },
  {
    connector: "rss",
    name: "npm Status",
    url: "https://status.npmjs.org/history.rss",
    source_kind: "status",
    topic: "tech",
    publisher_entity: { name: "npm", kind: "product" },
  },
  {
    connector: "rss",
    name: "Slack Status",
    url: "https://status.slack.com/feed/rss",
    source_kind: "status",
    topic: "tech",
    publisher_entity: { name: "Slack", kind: "company" },
  },
  {
    connector: "rss",
    name: "OpenAI Status",
    url: "https://status.openai.com/history.rss",
    source_kind: "status",
    topic: "ai",
    publisher_entity: { name: "OpenAI", kind: "company" },
  },
  {
    connector: "rss",
    name: "Anthropic Status",
    url: "https://status.anthropic.com/history.rss",
    source_kind: "status",
    topic: "ai",
    publisher_entity: { name: "Anthropic", kind: "company" },
  },
  {
    connector: "rss",
    name: "AWS Status",
    url: "https://status.aws.amazon.com/rss/all.rss",
    source_kind: "status",
    topic: "tech",
    publisher_entity: { name: "AWS", kind: "company" },
  },
  {
    connector: "rss",
    name: "Google Cloud Status",
    url: "https://status.cloud.google.com/feed.atom",
    source_kind: "status",
    topic: "tech",
    publisher_entity: { name: "Google Cloud", kind: "product" },
  },
  {
    connector: "rss",
    name: "Vercel Status",
    url: "https://www.vercel-status.com/history.rss",
    source_kind: "status",
    topic: "tech",
    publisher_entity: { name: "Vercel", kind: "company" },
  },
  {
    connector: "rss",
    name: "Discord Status",
    url: "https://discordstatus.com/history.rss",
    source_kind: "status",
    topic: "tech",
    publisher_entity: { name: "Discord", kind: "company" },
  },
  {
    connector: "rss",
    name: "Atlassian Status",
    url: "https://status.atlassian.com/history.rss",
    source_kind: "status",
    topic: "tech",
    publisher_entity: { name: "Atlassian", kind: "company" },
  },
  // 第三轮补：云与 SaaS（tech）、模型厂商（ai）、游戏平台（gaming）
  {
    connector: "rss",
    // 3 条，同上
    name: "Cohere Status",
    url: "https://status.cohere.com/history.rss",
    source_kind: "status",
    topic: "ai",
    publisher_entity: { name: "Cohere", kind: "company" },
  },
  {
    connector: "rss",
    // 1 条：这家故障少，不是源坏了
    name: "Groq Status",
    url: "https://groqstatus.com/history.rss",
    source_kind: "status",
    topic: "ai",
    publisher_entity: { name: "Groq", kind: "company" },
  },
  {
    connector: "rss",
    name: "Perplexity Status",
    url: "https://status.perplexity.com/history.rss",
    source_kind: "status",
    topic: "ai",
    publisher_entity: { name: "Perplexity", kind: "company" },
  },
  {
    connector: "rss",
    name: "Replicate Status",
    url: "https://replicatestatus.com/history.rss",
    source_kind: "status",
    topic: "ai",
    publisher_entity: { name: "Replicate", kind: "company" },
  },
  {
    connector: "rss",
    name: "Datadog Status",
    url: "https://status.datadoghq.com/history.rss",
    source_kind: "status",
    topic: "tech",
    publisher_entity: { name: "Datadog", kind: "company" },
  },
  {
    connector: "rss",
    name: "DigitalOcean Status",
    url: "https://status.digitalocean.com/history.rss",
    source_kind: "status",
    topic: "tech",
    publisher_entity: { name: "DigitalOcean", kind: "company" },
  },
  {
    connector: "rss",
    name: "Dropbox Status",
    url: "https://status.dropbox.com/history.rss",
    source_kind: "status",
    topic: "tech",
    publisher_entity: { name: "Dropbox", kind: "company" },
  },
  {
    connector: "rss",
    name: "Figma Status",
    url: "https://status.figma.com/history.rss",
    source_kind: "status",
    topic: "tech",
    publisher_entity: { name: "Figma", kind: "company" },
  },
  {
    connector: "rss",
    name: "Fly.io Status",
    url: "https://status.flyio.net/history.rss",
    source_kind: "status",
    topic: "tech",
    publisher_entity: { name: "Fly.io", kind: "company" },
  },
  {
    connector: "rss",
    name: "Heroku Status",
    url: "https://status.heroku.com/feed",
    source_kind: "status",
    topic: "tech",
    publisher_entity: { name: "Heroku", kind: "product" },
  },
  {
    connector: "rss",
    name: "MongoDB Status",
    url: "https://status.mongodb.com/history.rss",
    source_kind: "status",
    topic: "tech",
    publisher_entity: { name: "MongoDB", kind: "company" },
  },
  {
    connector: "rss",
    name: "Netlify Status",
    url: "https://www.netlifystatus.com/history.rss",
    source_kind: "status",
    topic: "tech",
    publisher_entity: { name: "Netlify", kind: "company" },
  },
  {
    connector: "rss",
    name: "Oracle Cloud Status",
    url: "https://ocistatus.oraclecloud.com/history.rss",
    source_kind: "status",
    topic: "tech",
    publisher_entity: { name: "Oracle Cloud", kind: "product" },
  },
  {
    connector: "rss",
    name: "Reddit Status",
    url: "https://www.redditstatus.com/history.rss",
    source_kind: "status",
    topic: "tech",
    publisher_entity: { name: "Reddit", kind: "company" },
  },
  {
    connector: "rss",
    name: "Render Status",
    url: "https://status.render.com/history.rss",
    source_kind: "status",
    topic: "tech",
    publisher_entity: { name: "Render", kind: "company" },
  },
  {
    connector: "rss",
    name: "Sentry Status",
    url: "https://status.sentry.io/history.rss",
    source_kind: "status",
    topic: "tech",
    publisher_entity: { name: "Sentry", kind: "company" },
  },
  {
    connector: "rss",
    name: "Supabase Status",
    url: "https://status.supabase.com/history.rss",
    source_kind: "status",
    topic: "tech",
    publisher_entity: { name: "Supabase", kind: "company" },
  },
  {
    connector: "rss",
    name: "Twilio Status",
    url: "https://status.twilio.com/history.rss",
    source_kind: "status",
    topic: "tech",
    publisher_entity: { name: "Twilio", kind: "company" },
  },
  {
    connector: "rss",
    name: "Zoom Status",
    url: "https://status.zoom.us/history.rss",
    source_kind: "status",
    topic: "tech",
    publisher_entity: { name: "Zoom", kind: "company" },
  },
  {
    connector: "rss",
    name: "Epic Games Status",
    url: "https://status.epicgames.com/history.rss",
    source_kind: "status",
    topic: "gaming",
    publisher_entity: { name: "Epic Games", kind: "company" },
  },
  {
    connector: "rss",
    name: "Twitch Status",
    url: "https://status.twitch.tv/history.rss",
    source_kind: "status",
    topic: "gaming",
    publisher_entity: { name: "Twitch", kind: "company" },
  },
];
