/**
 * GENERATED — do not edit.
 * Source: co-located `.css` files under `shared/site-css/`.
 * Regenerate: `pnpm --filter @rewindom/builtin assemble:module-css`
 */

export const ARTICLE_CSS = `.doc-article-back{display:flex;width:fit-content;align-items:center;gap:.375rem;height:1.5rem;color:var(--muted-fg);font-size:.875rem;line-height:1.5rem;text-decoration:none}.doc-article-back:hover{color:var(--accent)}.doc-article-meta{display:flex;flex-wrap:wrap;align-items:center;gap:.75rem;margin-top:1.25rem;font-size:.875rem;color:var(--muted-fg)}.doc-tag{display:inline-flex;align-items:center;padding:.125rem .625rem;border:1px solid var(--border);border-radius:999px;color:var(--accent);font-size:.8125rem}.doc-article h1{font-size:2rem;font-weight:600;letter-spacing:-.02em;line-height:1.2;margin:.75rem 0 0}.doc-article-lead{color:var(--muted-fg);font-size:1.0625rem;line-height:1.6;margin:.75rem 0 0}.doc-article .prose{margin-top:2rem}.doc-article-center{text-align:center}.doc-article-center .doc-article-back{margin-inline:auto}.doc-article-center .doc-article-meta{justify-content:center}.doc-article-center .prose{text-align:left}.site-main:has(.doc-article)>.sec:first-child{padding-top:2rem}`;

export const LIST_CSS = `.doc-list-group+.doc-list-group{margin-top:2.5rem}.doc-list-group-title{font-size:.875rem;font-weight:600;letter-spacing:.06em;text-transform:uppercase;color:var(--fg);padding-bottom:.75rem;border-bottom:1px solid var(--border);margin:0 0 1rem}.doc-card{display:flex;flex-direction:column;gap:.375rem;height:100%;transition:border-color .15s ease,transform .15s ease}.doc-card:hover{border-color:color-mix(in srgb,var(--accent) 45%,var(--border));transform:translateY(-1px)}.doc-card .muted{margin-top:0}.doc-card-date{margin-top:auto;padding-top:.5rem;font-size:.8125rem;color:var(--muted-fg)}.doc-list-rows{list-style:none;margin:0;padding:0}.doc-list-rows li+li{border-top:1px solid var(--border)}.doc-list-rows a{display:flex;flex-direction:column;gap:.25rem;padding:.875rem 0;color:inherit;text-decoration:none}.doc-list-rows a:hover .title{color:var(--accent)}.doc-list-rows .title{font-weight:500}.doc-list-rows .muted{font-size:.9375rem}.doc-list-filter{display:inline-flex;align-items:center;gap:.5rem;margin-bottom:1.5rem;padding:.375rem .5rem .375rem .75rem;border:1px solid var(--border);border-radius:999px;background:var(--muted-bg);font-size:.875rem}.doc-list-filter-term{color:var(--muted-fg)}.doc-list-filter-clear{display:inline-flex;align-items:center;justify-content:center;width:1.25rem;height:1.25rem;border:0;border-radius:999px;background:transparent;color:var(--muted-fg);font-size:.75rem;line-height:1;cursor:pointer}.doc-list-filter-clear:hover{background:var(--border);color:var(--fg)}.doc-list-filter-clear:focus-visible{outline:2px solid var(--accent);outline-offset:1px}.doc-list-empty{margin:0;color:var(--muted-fg)}`;

export const NAV_CSS = `.doc-nav{font-size:.875rem;margin-inline:-.625rem}.doc-nav ul{list-style:none;margin:0;padding:0}.doc-nav li{margin:0}.doc-nav a{display:block;padding:.375rem .625rem;border-radius:.375rem;color:var(--muted-fg);text-decoration:none;line-height:1.5}.doc-nav a:hover{color:var(--fg);background:var(--muted-bg)}.doc-nav a[aria-current=page]{color:var(--accent);font-weight:500;background:color-mix(in srgb,var(--accent) 10%,transparent)}.doc-nav-title{margin:0 0 .75rem;padding:0 .625rem;font-size:.875rem;font-weight:600;line-height:1.5rem}.doc-nav-group+.doc-nav-group{margin-top:1.25rem}.doc-nav-group-title{margin:0 0 .25rem;padding:0 .625rem;font-size:.6875rem;font-weight:600;letter-spacing:.06em;line-height:1.5rem;text-transform:uppercase;color:var(--fg)}.doc-nav-group-title+ul{margin-left:.625rem;padding-left:.375rem;border-left:1px solid var(--border)}.doc-nav-group-title+ul a{border-radius:0 .375rem .375rem 0}@media(min-width:1024px){.doc-nav.is-sticky{position:sticky;top:5rem;max-height:calc(100vh - 7rem);overflow-y:auto}}`;

export const SEARCH_CSS = `.chrome-search{position:relative;display:inline-flex;align-items:center}.chrome-search>svg{position:absolute;left:.5rem;color:var(--muted-fg);pointer-events:none}.chrome-search input{width:12rem;height:2rem;padding:0 .5rem 0 1.875rem;border:1px solid var(--border);border-radius:.5rem;background:var(--bg);color:inherit;font:inherit;font-size:.875rem}.chrome-search input:focus-visible{outline:2px solid var(--accent);outline-offset:1px}.chrome-search input::-webkit-search-cancel-button{appearance:none}`;

export const TOC_CSS = `.doc-toc{font-size:.875rem;margin-inline:-.625rem}.doc-toc ul{list-style:none;margin:0;padding:0}.doc-toc a{display:block;padding:.375rem .625rem;border-radius:.375rem;color:var(--muted-fg);text-decoration:none;line-height:1.5}.doc-toc a:hover{color:var(--fg);background:var(--muted-bg)}.doc-toc-title{margin:0 0 .25rem;padding:0 .625rem;font-size:.6875rem;font-weight:600;letter-spacing:.06em;line-height:1.5rem;text-transform:uppercase;color:var(--fg)}.doc-toc-l3 a{padding-left:1.375rem;font-size:.8125rem}@media(min-width:1024px){.doc-toc.is-sticky{position:sticky;top:5rem;max-height:calc(100vh - 7rem);overflow-y:auto}}`;
